product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path("recherche/", views.search, name="search"),
    path("aliment/<str:product_name>", views.single, name="single"),
]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("www.urls", namespace="www")),
    path("", include("product.urls", namespace="product")),
    path("mon-compte/", include("account.urls", namespace="account")),
    path("becomeachef/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

www/urls.py
from django.urls import path

from . import views

app_name = "www"

urlpatterns = [
    path("", views.home, name="home"),
    path("mentions-legales/", views.legal_notice, name="legal-notice"),
    path("mail-envoye/", views.send_email, name="send-email"),
]

www/forms.py
from django import forms


class ContactForm(forms.Form):
    from_email = forms.EmailField(
        widget=forms.EmailInput(attrs={"placeholder": "email..."}),
        required=True,
    )
    subject = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "sujet..."}),
        required=True,
    )
    content = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "message..."}),
        required=True,
    )

www/views.py
import os

from django.shortcuts import render, HttpResponseRedirect

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from www.forms import ContactForm
from product.forms import SearchForm


def home(request):
    context = {}
    context["nav_search_form"] = SearchForm(auto_id="nav_%s")
    context["jumbotron_search_form"] = SearchForm(auto_id="jumbotron_%s")
    context["contact_form"] = ContactForm()
    return render(request, "www/home.html", context=context)


def legal_notice(request):
    context = {}
    context["nav_search_form"] = SearchForm(auto_id="nav_%s")
    return render(request, "www/legal-notice.html", context=context)


def send_email(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            from_email = form.cleaned_data["from_email"]
            subject = form.cleaned_data["subject"]
            content = form.cleaned_data["content"]
            message = Mail(
                from_email=from_email,
                to_emails='olivier.loustaunau@gmail.com',
                subject=subject,
                html_content=content
            )
            sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
            sg.send(message)
    return HttpResponseRedirect("/")

templates/www/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Accueil
{% endblock %}

{% block content %}
<section id="home-jumbotron" class="jumbotron d-flex align-items-center justify-items-center">
  <div class="container">
    <div class="d-flex flex-row justify-content-center">
      <h1>Du gras, oui, mais de qualité !</h1>
    </div>
    <div class="d-flex flex-row justify-content-center text-center">
      <h2>Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
    </div>
    <div class="d-flex flex-row justify-content-center">
      <form class="mt-5" action="{% url 'product:search' %}" method="post">
        {% csrf_token %}
        {{jumbotron_search_form.product_name}}
        {{jumbotron_search_form.media}}
        <input type="submit" value="Chercher">
      </form>
    </div>
  </div>
</section>
<section id="about" class="pattern pt-5 pb-5">
  <div class="container text-center">
    <h2>Colette et Remy</h2>
    <hr>
    <p class="mt-3">
      <strong>Pur Beurre</strong> est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy,
      que vous avez déjà certainement rencontrés dans notre excellent restaurant <strong>Ratatouille</strong>.
    </p>
    <div class="container mt-5">
      <div class="row">
      <div class="col-sm-12 col-md-6">
        <img src="{% static 'img/colette-tatou.png' %}" alt="Colette Tatou" height="150">
        <p>Colette</p>
      </div>
      <div class="col-sm-12 col-md-6">
        <img src="{% static 'img/remy.png' %}" alt="Remy" height="150">
        <p>Rémy</p>
      </div>
    </div>
    </div>
  </div>
</section>
<section id="contact" class="pt-5 pb-5">
  <div class="container text-center">
    <h2>Contactez-nous !</h2>
    <hr>
    <p class="mt-3">
      Vous pouvez nous contacter par téléphone de 8H à 17H. Par e-mail, une reponse sera donnée sous 2 jours ouvrés.
    </p>
    <div class="container mt-5">
      <div class="row">
        <div class="col-sm-12 col-md-12">
          <i class="fas fa-phone-alt"></i>
          <p>05 45 13 37 42</p>
        </div>
        <div class="col-sm-12 col-md-12">
          <form action="{% url 'www:send-email' %}" method="post">
              {% csrf_token %}
              <div class="row justify-content-center">
                <div class="col-3">
                  {{ contact_form.from_email }}
                </div>
                <div class="col-3">
                  {{ contact_form.subject }}
                </div>
              </div>
              <div class="row justify-content-center col-6 offset-3" id="mail-content">
                {{ contact_form.content }}
              </div>
              <div class="row justify-content-center col-6 offset-3">
                <button type="submit">Send</button>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/www/legal-notice.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Mentions Legales
{% endblock %}

{% block content %}
<div class="pattern-bg h-100">
  <div class="container h-100">
    <div class="d-flex align-items-center h-100">
      <div id="legal-notice">
        <h1>Mentions légales</h1>
        <h2 class="mt-3 mb-3">Site</h2>
        <ul>
          <li>Site internet (ci-après « le Site ») : désigne le site https://purbeurre.io/.</li>
        </ul>
        <h2 class="mb-3">Éditeur</h2>
        <ul>
          <li>Pur Beurre, SAS au capital de 1337,0€, dont le siège social est situé: Montmartre, Paris - France,
            représentée par Colette Tatou, en sa qualité de Président, immatriculée au RCS de Versailles, 123 456 789,
            TVA intracommunautaire : FR123456789</li>
          <li>Courriel de contact : contact@pur-beurre.io</li>
        </ul>
        <h2 class="mb-3">Hébergeur</h2>
        <ul>
          <li>Le Site est hébergé par Heroku, dont le siège est situé 650 7th St, San Francisco, CA, 94103, United States.</li>
        </ul>
        <h2 class="mb-3">Protection des données</h2>
        <ul class="mb-5">
          <li>Un délégué à la protection des données : John Doe, security@purbeurre.io, est à votre disposition pour toute question relative à la protection de vos données personnelles.</li>
          <li>Nous respectons votre vie privee et vos données, il vous est possible de supprimer votre compte a tout moment sur votre profil.</li>
        </ul>
        <h2>Licences</h2>
        <ul class="mb-5">
          <li>Motif en fond de page créé par <a href="https://www.freepik.com/free-photos-vectors/background">Freepik</a></li>
          <li>Thème bootstrap par <a href="https://startbootstrap.com/themes/creative/">Start Bootstrap</a></li>
        </ul>
      </div>
    </div>
  </div>

</div>
{% endblock %}