account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "account"

urlpatterns = [
    path("", views.profile, name="profile"),
    path("inscription/", views.signup, name="signup"),
    path("mes-favoris/", views.favorites, name="favorites"),
    path("ajax/ajout-favoris/", views.add_favorite, name="add_favorite",),
    path("retirer-favori/", views.remove_favorite, name="remove_favorite"),
    path("supprimer-mon-compte/", views.delete_account, name="delete_account"),
    path(
        "connexion/",
        auth_views.LoginView.as_view(template_name="account/login.html"),
        name="login",
    ),
    path(
        "deconnexion/",
        auth_views.LogoutView.as_view(template_name="account/logged_out.html"),
        name="logout",
    ),
    path(
        "changer-mot-de-passe/",
        auth_views.PasswordChangeView.as_view(
            template_name="account/password_change.html", success_url="/",
        ),
        name="password_change",
    ),
    path(
        "mot-de-passe-change/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="account/password_change_done.html"
        ),
        name="password_change_done",
    ),
]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path("recherche/", views.search, name="search"),
    path("aliment/<str:product_name>", views.single, name="single"),
]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("www.urls", namespace="www")),
    path("", include("product.urls", namespace="product")),
    path("mon-compte/", include("account.urls", namespace="account")),
    path("becomeachef/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

www/urls.py
from django.urls import path

from . import views

app_name = "www"

urlpatterns = [
    path("", views.home, name="home"),
    path("mentions-legales/", views.legal_notice, name="legal-notice"),
    path("mail-envoye/", views.send_email, name="send-email"),
]

templates/includes/_footer.html
<footer class="pb-3 pt-3">
  <div class="container text-center">
    <span class="mr-5">
        <a href="{% url 'www:legal-notice' %}">Mentions légales</a>
    </span>
    <span class="ml-5">
      <a href="{% url 'www:home' %}#contact">Contact</a>
    </span>
  </div>
</footer>

templates/includes/_forms.html
{% load static %}
{% load i18n %}

{% for field in form %}
<div class="form-group">
  <div class="mx-auto">
    <label for="{{ field.id_for_label }}">{% trans field.label %}</label>
  </div>
  <div class="mx-auto">
    {{ field }}
  </div>
</div>
{% endfor %}

templates/includes/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand ml-5" href="{% url 'www:home' %}">
      <img id="logo" src="{% static 'img/logo_pur_beurre.png'%}" alt="Pur Beurre" width="50" height="50">
      <span id="nav-title" class="nav-dark">Pur Beurre</span>
    </a>
    <button class="navbar-toggler mr-5" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="mr-3 ml-auto" action="{% url 'product:search' %}" method="post">
        {% csrf_token %}
        {{ nav_search_form.product_name }}{{ nav_search_form.media }}
      </form>
      <ul class="navbar-nav mr-5">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link nav-dark" href="{% url 'account:profile' %}">
            <i class="fas fa-user"></i>
          </a>
        </li>
        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link nav-dark" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'account:signup' %}">Inscription</a>
            <a class="dropdown-item" href="{% url 'account:login' %}">Connexion</a>
          </div>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link nav-dark" href="{% url 'account:favorites' %}">
            <i class="fas fa-carrot"></i>
          </a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link nav-dark" href="{% url 'account:logout' %}">
            <i class="fas fa-sign-out-alt"></i>
          </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>