account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "account"

urlpatterns = [
    path("", views.profile, name="profile"),
    path("inscription/", views.signup, name="signup"),
    path("mes-favoris/", views.favorites, name="favorites"),
    path("ajax/ajout-favoris/", views.add_favorite, name="add_favorite",),
    path("retirer-favori/", views.remove_favorite, name="remove_favorite"),
    path("supprimer-mon-compte/", views.delete_account, name="delete_account"),
    path(
        "connexion/",
        auth_views.LoginView.as_view(template_name="account/login.html"),
        name="login",
    ),
    path(
        "deconnexion/",
        auth_views.LogoutView.as_view(template_name="account/logged_out.html"),
        name="logout",
    ),
    path(
        "changer-mot-de-passe/",
        auth_views.PasswordChangeView.as_view(
            template_name="account/password_change.html", success_url="/",
        ),
        name="password_change",
    ),
    path(
        "mot-de-passe-change/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="account/password_change_done.html"
        ),
        name="password_change_done",
    ),
]

product/urls.py
from django.urls import path
from . import views

app_name = "product"

urlpatterns = [
    path("recherche/", views.search, name="search"),
    path("aliment/<str:product_name>", views.single, name="single"),
]

pur_beurre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("www.urls", namespace="www")),
    path("", include("product.urls", namespace="product")),
    path("mon-compte/", include("account.urls", namespace="account")),
    path("becomeachef/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

www/urls.py
from django.urls import path

from . import views

app_name = "www"

urlpatterns = [
    path("", views.home, name="home"),
    path("mentions-legales/", views.legal_notice, name="legal-notice"),
    path("mail-envoye/", views.send_email, name="send-email"),
]

product/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)


class Product(models.Model):
    product_name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)
    image_url = models.URLField(max_length=255)
    nova_group = models.CharField(max_length=1)
    nutriscore_grade = models.CharField(max_length=1)
    saturated_fat_100g = models.DecimalField(
        max_digits=6, decimal_places=3, null=True
    )
    fat_100g = models.DecimalField(max_digits=6, decimal_places=3, null=True)
    salt_100g = models.DecimalField(max_digits=6, decimal_places=3, null=True)
    sugars_100g = models.DecimalField(
        max_digits=6, decimal_places=3, null=True
    )
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.product_name

    def find_substitute(self):
        res = list()
        product_categories = set(self.categories.all())
        for product in Product.objects.filter(
            nutriscore_grade__lt=self.nutriscore_grade
        ).order_by("nutriscore_grade"):
            if (
                len(
                    product_categories.intersection(
                        set(product.categories.all())
                    )
                )
                > 4
            ):
                res.append(product)
        return res[:20]

product/forms.py
from django import forms


class SearchForm(forms.Form):
    product_name = forms.CharField(max_length=100)

product/views.py
from django.shortcuts import render, HttpResponseRedirect

from .models import Product
from .forms import SearchForm


def search(request):
    context = {}
    context["nav_search_form"] = SearchForm(auto_id="nav_%s")
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            product_name = form.cleaned_data["product_name"]
            product = Product.objects.filter(
                product_name__icontains=product_name
            )
            if product:
                context["product"] = product[0]
                context["substitutes"] = product[0].find_substitute()
            return render(
                request, "product/search_results.html", context=context
            )
    return HttpResponseRedirect("/")


def single(request, product_name):
    context = {}
    context["nav_search_form"] = SearchForm(auto_id="nav_%s")
    context["product"] = Product.objects.filter(
        product_name__iexact=product_name
    )[0]
    return render(request, "product/single.html", context=context)

templates/product/search_results.html
{% extends 'base.html' %}

{% block title %}
Resultats
{% endblock %}

{% block content %}
{% if product %}
<section id="single-jumbotron" class="jumbotron jumbotron-fluid d-flex align-items-center" style="background-image: url('{{ product.image_url }}');background-size: contain;background-repeat: no-repeat;">
  <div class="container text-right">
    <h1>{{ product.product_name|title }}</h1>
  </div>
</section>
{% endif %}
<div id="search-results" class="pattern-bg pt-5">
  <div class="container">
    {% if substitutes %}
    <h2 class="text-center">Vous pouvez remplacer cet aliment par</h2>
    <div class="row">
      {% for substitute in substitutes %}
      <div class="col-lg-3">
        <div class="product-card-wrapper">
          <div class="card product-card justify-content-center align-items-center">
            <div class="card-body d-flex">
              <img class="img-fluid product-thumbnail align-self-center" src="{{ substitute.image_url }}" alt="{{ substitute.product_name|title }}">
            </div>
            <div class="card-footer">
              <div class="d-flex flex-row justify-content-center">
                <p id="{{ substitute.id }}"><a href="{% url 'product:single' substitute.product_name %}">{{ substitute.product_name|title }}</a></p>
              </div>
              <div class="d-flex flex-row justify-content-center">
                <p><a class="favorite-link" href="{% url 'account:add_favorite' %}">Sauvegarder</a></p>
              </div>
            </div>
            {% if substitute.nutriscore_grade == "a" %}
            <div class="card-badge card-badge-dark-green">{{ substitute.nutriscore_grade.capitalize }}</div>
            {% elif substitute.nutriscore_grade == "b" %}
            <div class="card-badge card-badge-green">{{ substitute.nutriscore_grade.capitalize }}</div>
            {% elif substitute.nutriscore_grade == "c" %}
            <div class="card-badge card-badge-yellow">{{ substitute.nutriscore_grade.capitalize }}</div>
            {% elif substitute.nutriscore_grade == "d" %}
            <div class="card-badge card-badge-orange">{{ substitute.nutriscore_grade.capitalize }}</div>
            {% else %}
            <div class="card-badge card-badge-red">{{ substitute.nutriscore_grade.capitalize }}</div>
            {% endif %}
          </div>
        </div>
      </div>
      {% if forloop.counter|divisibleby:"4" %}
    </div>
    <div class="row">
      {% endif %}
      {% endfor %}
      {% else %}
      <p>Aucun résultat</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

  {% block ajax %}
  <script type="text/javascript">
    $(document).ready(function() {
      $('.favorite-link').click(function(event) {
        event.preventDefault();
        $.ajax({
          url: "{% url 'account:add_favorite' %}",
          type: "GET",
          data: {
            'product_id': this.parentElement.parentElement.previousElementSibling.children[0].id,
          },
          success: function(json) {
          },
          error: function(json) {
            window.location.replace("/mon-compte/connexion");
          },
        });
      });
    });
  </script>
  {% endblock %}

templates/product/single.html
{% extends "base.html" %}
{% load static %}
{% load round_float %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}
<section id="single-jumbotron" class="jumbotron jumbotron-fluid d-flex align-items-center" style="background-image: url('{{ product.image_url }}');background-size: contain;background-repeat: no-repeat;">
  <div class="container text-right">
    <h1>{{ product.product_name|title }}</h1>
  </div>
</section>
<div class="pattern-bg pb-5">
  <div id="single-container" class="container">
    <div class="row">
      <div id="nutriscore-single" class="col-xs-12 col-md-6">
        <h3>Nutriscore</h3>
        {% if product.nutriscore_grade == "a" %}
        <img src="{% static 'img/nutriscore-a.svg' %}" alt="A">
        {% elif product.nutriscore_grade == "b" %}
        <img src="{% static 'img/nutriscore-b.svg' %}" alt="B">
        {% elif product.nutriscore_grade == "c" %}
        <img src="{% static 'img/nutriscore-c.svg' %}" alt="C">
        {% elif product.nutriscore_grade == "d" %}
        <img src="{% static 'img/nutriscore-d.svg' %}" alt="D">
        {% else %}
        <img src="{% static 'img/nutriscore-e.svg' %}" alt="E">
        {% endif %}
      </div>
      <div id="nutritional-single" class="col-xs-12 col-md-6">
        <h3>Repères nutritionnels pour 100 g</h3>
        <p>Matières grasses / Lipides: <strong>{{ product.fat_100g|round_float }} g</strong></p>
        <p>Acides gras saturés: <strong>{{ product.saturated_fat_100g|round_float }} g</strong></p>
        <p>Sucres: <strong>{{ product.sugars_100g|round_float }} g</strong></p>
        <p>Sel: <strong>{{ product.salt_100g|round_float }} g</strong></p>
      </div>
    </div>
    <div class="row justify-content-center mt-5">
      <a class="custom-button" href="{{ product.url }}" target="_blank">Voir la fiche d'OpenFoodFacts</a>
    </div>
  </div>
</div>

{% endblock %}